// <auto-generated />
using System;
using DogShelter.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogShelter.Migrations
{
    [DbContext(typeof(DogShelterDbContext))]
    [Migration("20210510063203_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DogShelter.Model.Dog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShelterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ShelterId");

                    b.ToTable("Dog");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 1,
                            Breed = "Jack Russel Terrier",
                            Name = "Zsuli",
                            ShelterId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Age = 14,
                            Breed = "Beagle",
                            Name = "Lulu",
                            OwnerId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Age = 1,
                            Breed = "Cuki",
                            Name = "Füge",
                            ShelterId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Age = 15,
                            Breed = "Valami",
                            Name = "Guszti",
                            OwnerId = 2L
                        });
                });

            modelBuilder.Entity("DogShelter.Model.Shelter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Shelter");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Gödöllő",
                            Name = "Gödöllői menhely",
                            OwnerId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Szada",
                            Name = "Lelenc menhely",
                            OwnerId = 3L
                        });
                });

            modelBuilder.Entity("DogShelter.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Ákos",
                            Phonenumber = "030134231"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Dani",
                            Phonenumber = "244234234"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Virág",
                            Phonenumber = "244232334"
                        });
                });

            modelBuilder.Entity("DogShelter.Model.Dog", b =>
                {
                    b.HasOne("DogShelter.Model.User", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerId");

                    b.HasOne("DogShelter.Model.Shelter", "Shelter")
                        .WithMany("Dogs")
                        .HasForeignKey("ShelterId");
                });

            modelBuilder.Entity("DogShelter.Model.Shelter", b =>
                {
                    b.HasOne("DogShelter.Model.User", "Owner")
                        .WithMany("Shelters")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
