// <auto-generated />
using DogShelter.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogShelter.Migrations
{
    [DbContext(typeof(DogShelterDbContext))]
    [Migration("20210509113239_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DogShelter.Model.Dog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dog");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Age = 14,
                            Breed = "Beagle",
                            Name = "Lulu"
                        },
                        new
                        {
                            Id = 1L,
                            Age = 1,
                            Breed = "Jack Russel Terrier",
                            Name = "Zsuli"
                        },
                        new
                        {
                            Id = 3L,
                            Age = 1,
                            Breed = "cuki",
                            Name = "Füge"
                        },
                        new
                        {
                            Id = 4L,
                            Age = 15,
                            Breed = "Valami",
                            Name = "Guszti"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
